### ISSUE TITLE
Getting Test coverage for code climate 

### ISSUE THREAD

**Issue by vorasagar7** [p632-sp-2017/microservice-catalog-frontend#2]
_From @arpitkh12 on February 26, 2017 21:12_

Update pom.xml to get code climate test coverage.

_Copied from original issue: p632-sp-2017/microservice-catalog-frontend-old#18_

**Comment by arpitkh12** [comment]
Updated the .travis.yml. Doesnot picks up yarn. So always make sure that use npm ``` npm install -g codeclimate-test-reporter``` and not yarn
