### ISSUE TITLE
Include the basic layout into the spring boot react app.

### ISSUE THREAD

**Issue by njetty** [p632-sp-2017/microservice-catalog-frontend#4]

**Comment by njetty** [comment]
Updated the react app to include the sample layout

<img width="1400" alt="screenshot 2017-02-14 20 00 55" src="https://cloud.githubusercontent.com/assets/15404338/22988376/d956e34a-f37f-11e6-9e79-4319ffa51ae8.png">

**Comment by vorasagar7** [comment]
This issue was moved to p632-sp-2017/microservice-catalog-frontend#9
