### ISSUE TITLE
Filter table based on the search box value

### ISSUE THREAD

**Issue by gmadhwani01** [p632-sp-2017/microservice-catalog-frontend#8]
Filter the rows based on input in the search box.
![image](https://cloud.githubusercontent.com/assets/25439300/23049399/c0556af0-f489-11e6-9839-4c2849885a93.png)

**Comment by gmadhwani01** [comment]
Working fine hence closing the issue.

**Comment by vorasagar7** [comment]
This issue was moved to p632-sp-2017/microservice-catalog-frontend#11
