### ISSUE TITLE
Code Coverage not reported to code climate

### ISSUE THREAD

**Issue by njetty** [p632-sp-2017/microservice-catalog-frontend#9]
Travis CI is not reporting the code-coverage to the code climate

**Comment by njetty** [comment]
The latest commit to the travis.yml is solving the issue 

![](https://www.dropbox.com/s/31pqt0cq9slzg4q/Screenshot%202017-02-19%2016.24.12.png?raw=1)

**Comment by vorasagar7** [comment]
This issue was moved to p632-sp-2017/microservice-catalog-frontend#12
